name: Say hello when issues are created
on:
  issues:
    types: [opened]

jobs:
  say_hi:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Octocat"
  fetch_issues:
    name: Fetch GitHub Issues
    runs-on: ubuntu-latest
    steps:
      - name: cURL GitHub Issues
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/dcchambers/hello-github-actions/issues
